// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnegsckjwdqiescywcna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuZWdzY2tqd2RxaWVzY3l3Y25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDk2OTgsImV4cCI6MjA4NTYyNTY5OH0.pSx5MmWVn3FbLMe5ZFjo5hIJsVxUNIJrMRfhw3OX96s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});